MYARCH/MYARCH/MYARCH.WEB/Controllers/SiteController.cs
using MYARCH.DATA.UnitofWork;
using MYARCH.DTO.EEntity;
using MYARCH.SERVICES.Interfaces;
using MYARCH.UTILITIES.ImageOperations;
using MYARCH.UTILITIES.SessionOperations;
using MYARCH.UTILITIES.StringOperations;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MYARCH.WEB.Controllers
{
    public class SiteController : PublicController
    {
        private readonly IUnitofWork _uow;
        private readonly IPostService _postService;
        private readonly ICategoryService _categoryService;
        private readonly IUserService _userService;

        public SiteController(IUnitofWork uow,
            IPostService postService,
            ICategoryService categoryService,
             IUserService userService)
            : base(uow)
        {
            _uow = uow;
            _postService = postService;
            _categoryService = categoryService;
            _userService = userService;
        }
        public static string html = null;
        public ActionResult Index()
        {
            Session["a"] = 0;
            html = null;
            var result = _categoryService.GetCategories();
            foreach (var item in result)
            {
                html += "<li><a href='/" + StringManager.ToSlug(item.Name) + "-" + item.Id + "' style='color:" + item.Color + "!important;'><i class='" + item.Icon + "'></i>" + item.Name + "</a></li>";
            }
            return View(_postService.GetPostAll(null, 0));
        }

        public ActionResult PostList(int categoryId, string categoryName)
        {
            Session["pageNumber"] = 0;
            Session["categoryId"] = categoryId;
            Session["IsEmpty"] = _postService.GetPostAll(categoryId, 1);
            return View(_postService.GetPostAll(categoryId, 0));

        }
        public ActionResult PostMore()
        {
            Session["pageNumber"] = (int)Session["pageNumber"] + 1;
            var list = _postService.GetPostAll((Int32)Session["categoryId"], (Int32)Session["pageNumber"]);
            Session["IsEmpty"] = _postService.GetPostAll((Int32)Session["categoryId"], (Int32)Session["pageNumber"] + 1);
            return PartialView("~/Views/Shared/PostMore.cshtml", list); 
        }
        public ActionResult PostDetail(string categoryName, string slug)
        {
            EPostDetailPageDTO pdp = new EPostDetailPageDTO();
            pdp.PostDetail = _postService.GetPostDetailBySlug(slug);
            pdp.PostList = _postService.GetPostAll(null, 0).Take(5).ToList();
            return View(pdp);
        }

        public FileContentResult ProfileImageView(int id, int? w, int? h)
        {
            return new FileContentResult(ImageManager.ConvertToSize(_userService.GetUserImage(id), w, h), "image/png");
        }

        public ActionResult PostImageView(int id, int? w, int? h)
        {
            return new FileContentResult(ImageManager.ConvertToSize(_postService.GetPostImageById(id), w, h), "image/png");
        }

    }
}

MYARCH/MYARCH/MYARCH.WEB/Views/Site/Index.cshtml
@{
    ViewBag.Title = "Teknoloji Makaleleri";
    Layout = "~/Views/Shared/_Site_Layout.cshtml";
}
@model List<MYARCH.DTO.EEntity.EPostUserDTO>
<div class="row">
    @foreach (var item in Model)
    {  
        <div class="col-lg-4">
        <div class="card hovercard" >
            <div class="cardheader bgGreen" style="background-image:url(@item.PostImageUrl)">
                <div class="post-overlay"></div>
                <div class="title" style="text-align:left;position:absolute; bottom:0; color:#fff;">
                    <img class="img-responsive img-circle " src="@item.UserImageUrl/50/50"/>
                    <div class="user-info"><h4>@item.FullName<sm>@item.Job</sm></h4></div>
                </div>
            </div>
            <div class="info">
                <div class="title">@item.Title</div>
            </div>
            <hr />
            <div class="info">
                <div class="short-description">@item.ShortDescription</div>
            </div>
            <hr />
            <div class="bottom">
                <a href="/@MYARCH.UTILITIES.StringOperations.StringManager.ToSlug(item.CategoryName)/@item.Slug">   
                  <i class="fa fa-external-link pull-left"></i> Git</a>
                <a href="//facebook.com/sharer/sharer.php?u=@Request.Url@MYARCH.UTILITIES.StringOperations.StringManager.ToSlug(item.CategoryName)/@item.Slug" target="_blank">
                    <i class="fa fa-facebook pull-right"></i>
                </a>
                <a href="#">
                    <i class="fa fa-twitter pull-right"></i>
                </a>
                <a href="#">   <i class="fa fa-google-plus pull-right"></i></a>
            </div>
        </div>
    </div>

    }

</div>

MYARCH/MYARCH/MYARCH.WEB/Views/Site/PostDetail.cshtml
@{
    ViewBag.Title = "PostDetail";
    Layout = "~/Views/Shared/_Site_Layout.cshtml";
}
@model MYARCH.DTO.EEntity.EPostDetailPageDTO
<div class="container">
    <div class="row">
        <div class="col-lg-8">
            <div class="panel panel-default panel-google-plus card-shadow"> 
                <div class="panel-heading">
                    <img class="img-circle pull-left" src="@Model.PostDetail.UserImageUrl/70/70">
                    <h3>@Model.PostDetail.FullName</h3>
                    <h5><span>@Model.PostDetail.Job</span> <br /> <span>@Model.PostDetail.CreatedOnString</span> </h5>
                </div>
                <div class="panel-body">
                    <h2><em>@Model.PostDetail.Title</em></h2>
                   @MvcHtmlString.Create(HttpUtility.HtmlDecode(Model.PostDetail.PostContent))
                </div>
                <div class="panel-footer"> 
                    <a href="//facebook.com/sharer/sharer.php?u=@Request.Url" class="btn btn-default" target="_blank">
                        <i class="fa fa-facebook pull-right"></i>
                    </a>
                    <a href="#" class="btn btn-default">
                        <i class="fa fa-twitter pull-right"></i>
                    </a>
                    <a href="#" class="btn btn-default">   <i class="fa fa-google-plus pull-right"></i></a>
                </div> 
            </div>
        </div>
        <div class="col-lg-4">
            <div class="right-sidebar"> 
                @foreach (var item in Model.PostList)
                {
                    <div class=" panel post">
                        <div class="post-img-content">
                            <img src="@item.PostImageUrl" class="img-responsive" />
                            <span class="post-title">
                                <a href="/@item.CategoryName/@item.Slug">@item.Title</a><br />
                            </span>
                        </div>
                    </div>
                } 
            </div>
        </div>

    </div>
</div>

MYARCH/MYARCH/MYARCH.WEB/Views/Site/PostList.cshtml
@{
    ViewBag.Title = "CategoryList";
    Layout = "~/Views/Shared/_Site_Layout.cshtml";
}
<style>
    body {
        padding-top: 200px;
    }
</style>
@section breadCrumb{
    <div class="collapse navbar-collapse site-title">
        <h1>@Model[0].CategoryName</h1>
    </div>
}
@model List<MYARCH.DTO.EEntity.EPostUserDTO>

<div id="postList" class="row row-margin-bottom">
    @foreach (var item in Model)
    {
        <div class="col-md-5 lib-item" style="margin-right:20px;">
            <div class="lib-panel">
                <div class="row box-shadow">
                    <div class="col-md-6">
                        <img class="lib-img-show" src="@item.PostImageUrl" style="height:190px;">
                    </div>
                    <div class="col-md-6">
                        <div class="lib-row lib-header">
                            <a href="/@MYARCH.UTILITIES.StringOperations.StringManager.ToSlug(item.CategoryName)-@item.CategoryId/@item.Slug">
                                @item.Title
                            </a>
                            <div class="lib-header-seperator"></div>
                        </div>
                        <div class="lib-row lib-desc">
                            @item.ShortDescription
                        </div>
                    </div>
                </div>
            </div>
        </div>
    }
</div>
<script src="~/Assets/Scripts/jquery.unobtrusive-ajax.min.js"></script>
@using (Ajax.BeginForm("PostMore", "Site", new AjaxOptions { HttpMethod = "Post", UpdateTargetId = "postList", InsertionMode = InsertionMode.InsertAfter }))
{
    <input id="btnPostMore" type="submit" class="btn btn-default" value="Daha Fazla Göster" style="width: 100%;" />
}
@if (((List<MYARCH.DTO.EEntity.EPostUserDTO>)Session["IsEmpty"]).Count == 0)
{
    <style>
        #btnPostMore {
            display: none;
        }
    </style>
}